export const SERVICES = [
    '(C/PINO SANTO 1) MAÑANA - TRÁMITES MUNICIPALES',

    '(C/PINO SANTO 1) TARDE - TRÁMITES MUNICIPALES',

    '(C/PORTUGAL 17) MAÑANA - TRÁMITES MUNICIPALES',

    '(C/PORTUGAL 17) TARDE - TRÁMITES MUNICIPALES',
];